FROM bitnami/spark:latest

USER root
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

RUN curl -o /opt/bitnami/spark/jars/mongo-spark-connector_2.12-10.1.1.jar \
    https://repo1.maven.org/maven2/org/mongodb/spark/mongo-spark-connector_2.12/10.1.1/mongo-spark-connector_2.12-10.1.1.jar

COPY sparkekafka.py /opt/bitnami/spark/work/
COPY postgresql-42.7.5.jar /opt/bitnami/spark/jars/

# Instale o pymongo
RUN apt-get update && apt-get install -y python3-pip && pip3 install pymongo && pip3 install pandas && pip3 install numpy && pip3 install scikit-learn 

# Retorne para o usuário padrão
USER 1001